#! /bin/sh

sxhkd &

bspc monitor VGA1 -d 0 1 2 3 4 5

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config click_to_focus true
bspc config auto_alternate true
bspc config auto_cancel true

bspc rule -a URxvt state=floating
bspc rule -a Firefox desktop='^1'
bspc rule -a qutebrowser desktop='^1'
bspc rule -a mpv state=floating desktop='^5'
bspc rule -a Pcmanfm state=floating
bspc rule -a Mousepad state=floating
bspc rule -a feh state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Lxappearance state=floating center=true
bspc rule -a wps state=monocle desktop='^4'

urxvtd -q -o -f &
/home/traptivist/.bin/bspwmcolor.sh
dunst
/home/traptivist/.config/polybar/launch.sh
redshift -l -2.23:-80.85
